### ISSUE TITLE
Incorrect definition of server's default port

### ISSUE THREAD

**Issue by akito1986** [akito1986/haproxy_parser#3]
Server's default port is defined by frontend's port.  
Although when server's port is undefined, this tool have occured below errors.

```
     HaproxyParser::FormatChecker::FormatError:
       [ALERT] 294/173343 (24978) : parsing [/var/folders/64/sxvr_4hd6bb0chkpvkfk7t_m0000gn/T/haproxy_parser20161021-24937-1iukx9s:70] : server 10.21.0.160:80 has neither service port nor check port nor tcp_check rule 'connect' with port information. Check has been disabled.
       [ALERT] 294/173343 (24978) : Error(s) found in configuration file : /var/folders/64/sxvr_4hd6bb0chkpvkfk7t_m0000gn/T/haproxy_parser20161021-24937-1iukx9s
       [ALERT] 294/173343 (24978) : Fatal errors found in configuration.
     # ./lib/haproxy_parser/format_checker.rb:15:in `run'
     # ./lib/haproxy_parser/config.rb:17:in `check_format!'
     # ./lib/haproxy_parser/config.rb:21:in `parse'
     # ./spec/lib/haproxy_parser/config_spec.rb:18:in `block (3 levels) in <top (required)>'
     # ./spec/lib/haproxy_parser/config_spec.rb:53:in `block (4 levels) in <top (required)>'
```

Maybe, default value's definition is incorrect.

**Comment by akito1986** [comment]
Tentatively, I change server's port required.
